FROM postgres:14.4

# MAINTAINER Sanjiv Kumar "mr.san.kumar@gmail.com"
# By copying it to below directory, init.sql runs each time the postgres container is started.
COPY init.sql /docker-entrypoint-initdb.d